<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Dotnet.Foundation</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5"/>
        <PackageReference Include="MongoDB.Driver" Version="3.12.0"/>
        <PackageReference Include="Scrutor" Version="7.0.0"/>
    </ItemGroup>
</Project>
